# Settings.yml

---
conf.py:
  copyright: 2017
  project: Extension Compatibility Check
  version: 1.0.0
  release: 1.0.0
  html_theme_options:
    github_repository: schams-net/extension_compatibility_check
    github_branch: master
    t3install:
    - http://docs.typo3.org/typo3cms/InstallationGuide/
    - null
  intersphinx_mapping:
    _results-and-actions:
    - https://docs.typo3.org/typo3cms/extensions/_results-and-actions/
    - null
...
